# Generated by Django 5.2.7 on 2025-12-01 15:36

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformauser',
            name='joined_date',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 11, 25, 0, 0, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
    ]