name: Generate and Deploy Docs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Build documentation
        run: |
          mkdir -p docs
          pandoc README.md -o docs/index.html

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
